services:
  db:
    container_name: db
    image: mysql:8.0
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=videowall
      - MYSQL_ROOT_PASSWORD=password
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-ppassword"]
      interval: 5s
      timeout: 5s
      retries: 10

  videowall-api:
    container_name: videowall-api
    image: videowall-api:latest
    privileged: true
    restart: unless-stopped
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - ConnectionStrings__Default=Server=db;Database=videowall;User=root;Password=password;
    volumes:
      - ./storage/timelapse:/app/timelapse-storage
    ports:
      - "5001:5001"

  videowall:
    container_name: videowall
    image: videowall:latest
    privileged: true
    restart: unless-stopped
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - videowall-api
    environment:
      - BACKEND_URL=http://videowall-api:5001
    ports:
      - "3000:3000"

volumes:
  db_data:
